cloud:
  aws:
    credentials:
      access-key:
      secret-key:
    region:
      use-default-aws-region-chain: true
      static:
    stack:
      auto: false

application:
  bucket:
    name: springs3chitimoju

logging:
  level:
    com:
      amazonaws:
        internal:
          InstanceMetadataServiceResourceFetcher: error
        util:
          EC2MetadataUtils: error


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 9090

