cloud:
  aws:
    credentials:
      access-key: AKIAVRNYCWTHQBPDMWX4
      secret-key: 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
    region:
      use-default-aws-region-chain: true
      static: us-east-1
    stack:
      auto: false

application:
  bucket:
    name: springs3chitimoju

logging:
  level:
    com:
      amazonaws:
        internal:
          InstanceMetadataServiceResourceFetcher: error
        util:
          EC2MetadataUtils: error


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 9090

